version: '3'
services:
  docker-picamera-example:
    image: imagem3
    #build: 
      
      #dockerfile: Dockerfile
      #: . 
    container_name: docker-picamera-example
    command: python3 camera.py
    volumes:
      - "/home/pi/Images_Cam:/home/pi/Images_Cam"
    devices:
      - "/dev/vchiq:/dev/vchiq"
      - "/dev/vcsm:/dev/vcsm"





