version: '3'
services:
  docker-picamera-example:
    #build: 
    image: imagem5
      #dockerfile: Dockerfile
      #context: . 
    container_name: docker-picamera-example
    
    volumes:
      - "/home/pi/Images_Cam"
    devices:
      - "/dev/vchiq:/dev/vchiq"
      - "/dev/vcsm:/dev/vcsm"
    command: python3 camera.py




