version: '3'
services:
  docker-picamera-example:
    #build: 
    image: imagem7
      #dockerfile: Dockerfile
      #context: . 
    container_name: docker-picamera-examples
    command: python3 camera.py
    volumes:
      - "/home/pi/Images_Cam:/home/pi/Images_Cam"
    devices:
      - "/dev/vchiq:/dev/vchiq"
      - "/dev/vcsm:/dev/vcsm"
 
  phototovideo:
    build: 
    #image: imagem8
      dockerfile: Dockerfile2
      context: . 
    container_name: photo2video
    command: python3 ./video_converter.py 
    volumes:
      - "/home/pi/Images_Cam:/home/pi/Images_Cam"
      - "/home/pi/temp_video:/home/pi/temp_video"
    
