version: '3'
services:
  docker-picamera-example:
    #build: 
    image: imagem7
      #dockerfile: Dockerfile
      #context: . 
    container_name: docker-picamera-examples
    command: python3 camera.py
    volumes:
      - "/home/pi/Images_Cam:/home/pi/Images_Cam"
    devices:
      - "/dev/vchiq:/dev/vchiq"
      - "/dev/vcsm:/dev/vcsm"
 
  phototovideo:
    build: 
    #image: imagem8
      dockerfile: Dockerfile2
      context: . 
    container_name: photo4video
    environment:
      IMAGEIO_FFMPEG_EXE: /usr/bin/ffmpeg 
    command: python3 ./video_converter.py 
    volumes:
       - "/usr/lib:/usr/lib"
       - "/usr/local/lib:/usr/local/lib"
       - "/usr/bin/ffmpeg:/usr/bin/ffmpeg"
       - "/home/pi/Images_Cam:/home/pi/Images_Cam"
       - "/home/pi/temp_video:/home/pi/temp_video"
    
