version: '3'
services:
  docker-picamera-example:
    build: 
      #image: imagem3
      context: . 
    container_name: docker-picamera-example
    command: python3 picamera.py
    volumes:
      - '/home/pi/Images_Cam'
    devices:
      - '/dev/vchiq:/dev/vchiq'  
      - '/dev/vcsm:/dev/vcsm'   
      priveleged: true


