version: '3'
services:
  docker-picamera-example:
    build: 
      #image: imagem3
      dockerfile: Dockerfile
      context: . 
    container_name: docker-picamera-example
    command: python3 picamera.py
    devices:
      - "/dev/vchiq:/dev/vchiq"
      - "/dev/vcsm:/dev/vcsm"





